on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
    - name: Generating Makefiles
      run: cmake .
    - name: Compiling
      run: cmake --build .
  mingw:
    runs-on: windows-latest
    strategy:
      matrix:
        sys: [ mingw64, mingw32, ucrt64, clang64 ]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        release: false
        msystem: ${{matrix.sys}}
        pacboy: cc:p cmake:p ninja:p
    - uses: actions/checkout@v2
    - name: Generating Makefiles
      run: cmake .
    - name: Compiling
      run: cmake --build .
